### ISSUE TITLE
Physical Description

### ISSUE THREAD

**Issue by rtilla1** [lsulibraries/ldlxml#6]
to note that the records are pdfs create an 856 with a delimiter q that is "application/pdf"

**Comment by rtilla1** [comment]
to note that they were made from digitized microfilm, 
the seventh character of the leader must be m (most of them are a), but if it is changed, these will not be "text"  in <type of resource> but will instead be "software, multimedia". There may be other unintended changes--still researching what those will be.
Also, some correction need to be made to the 007...see comment below.

**Comment by rtilla1** [comment]
007 guidelines (cz#bn#nnnaubua)
00 = c
01 = z
02 = # 
03 = b (black and white)
04 = n
05 = # 
06-8 = nnn
09 = a
10 = u (unknown)
11 = b
12 = u
13 = a

**Comment by rtilla1** [comment]
Waiting to hear back from catalogers about conflict between leader character 7 as m or a...

**Comment by myqua** [comment]
added 856 q to all 856 with string proquest in it. deleted all existing 007 and replaced with 007 cz#bn@nnnaubua
